### PR TITLE
Remove the nginx version from the http header

### PR DESCRIPTION
**Pull request by auchri**
Improves security: http://serverfault.com/questions/214242/can-i-hide-all-server-os-info/214249

### CODE REVIEW

**Comment by richarvey** [comment]
Should this be a default setting?

**Comment by auchri** [comment]
I'm not sure about it.

**Comment by richarvey** [comment]
So this brought up a interesting conversation in the office. We agree it's a very good idea. We also thought its not default nginx behavior.

One suggestion is we could make this a flag to turn it on or off, does that sound sensible to you?

**Comment by auchri** [comment]
> One suggestion is we could make this a flag to turn it on or off, does that sound sensible to you?

Sounds fine to me. Maybe create a flag to turn the version on (off by default).

**Pull request closed without merging**
