### PR TITLE
respect webroot for all operations

### PR DESCRIPTION
**Pull request by russelltsherman**
it appears that providing webroot would have no bearing on other operations..
it seems reasonable that all operations should respect a custom webroot

### CODE REVIEW

**Comment by martinfrances107** [comment]
I think this covers all the places where the change is needed.
The patch is a welcome improvement.

+1 from me.

**Comment by richarvey** [comment]
I'll get this checked and merged, this was on my to do, so thanks for the help, much appreciated

**Comment by richarvey** [comment]
I'm going to make a patch to change $webroot to ${webroot} just for consistency. Also the pull script needs updating.

**Comment by richarvey** [comment]
Ok checking this through and a blanket change of this value doesn't work.

I think this is down to a miss understanding of the webroot variable.

webroot might be set to /var/www/html/public

in your git repo you would have a directory structure of:

- public
  -index.html
  - images
    - image.png
- scripts
- conf

So if you update all the variables in this way the rest of the site breaks. please have a look at [repo_layout](https://github.com/ngineered/nginx-php-fpm/blob/master/docs/repo_layout.md)

It may be that we need to update that first and then work through this.

I think people are confused (and this is my fault) and expect WEBROOT to be the repository root, its not. Web root is always a sub folder within /var/www/html/

I totally agree this needs doing, but we need to test all the bits first.

**Pull request closed without merging**
